### PR TITLE
Mobile navbar

### LINKED ISSUE #48: Header navbar component
# Acceptance Criteria
Add navbar functionality to header that was implemented in ticket #47. This navbar is only visible on mobile device resolutions.

### Related Features
- (BLOCKED BY) #47 Header component

### Design References
Desktop design:
https://xd.adobe.com/view/ae471f35-b465-4155-b95e-4c01bd61deef-fb14/

Mobile design:
https://xd.adobe.com/view/3640d8e0-d80d-43e5-b7d0-fe240a00644f-6313/

### PR DESCRIPTION
**Pull request by MoribundMedium**
Resolves #48

# Description of Changes
Adds a navbar to the mobile version of our site, fitting our design mockup: https://xd.adobe.com/view/3640d8e0-d80d-43e5-b7d0-fe240a00644f-6313/. The sliding transition animation is something I added, but should behave properly. The navbar is rendered `display: none;` when in desktop resolutions.

One thing to note: The hamburger and 'X' icons use the Font Awesome designs and don't match the icons in the mockup. Is this a big issue? I wasn't sure how to export the SVGs from the mockup.

## How Can I Test This?
Open up the test branch on Netlify and test the buttons in mobile resolutions (in Chrome, pull open the devtools with Ctrl+Shift+I and activate the device toolbar with Ctrl+Shift+M, then choose either "Responsive" resolution at the top or any mobile device on the list).

### CODE REVIEW

**Review by Hellrungj — CHANGES_REQUESTED** [review]
I found an issue with margining or padding when I use to develop tools to view mobile. Not sure why the site does that. It fixes itself when you click on the menu but if you exit out of dev tools with the menu collapsed the issue returns.
image

**Comment by itzsaga** [comment]
Following up on what @Hellrungj mentioned. You can see the horizontal scroll bar in this screen capture:
Kapture 2021-07-26 at 08 30 00
I haven't had time to dig into the code yet, however, it looks like the width of the screen is changing with the animation/menu sliding.

**Comment by MoribundMedium** [comment]
Thanks for the reviews @itzsaga and @Hellrungj! I fixed the issue by adding an `overflow-x: hidden;` rule to one of the sidenav's parents. I had to reassign its `position: relative;` parent at the same time but it should work!

https://github.com/nashvillefcc/nashvillefcc2020website/pull/82/commits/9fe6357bda5e5ce3e5b07e068ffc43f6fe26d923

**Review by Hellrungj — APPROVED** [review]
Looks great. Thank you for fixing that issue. 👍

**Review by itzsaga — APPROVED** [review]
LGTM!

**Pull request merged**
