### PR TITLE
Favicon

### PR DESCRIPTION
**Pull request by christianzoll**
Resolved merged conflicts with initial favicon PR

### CODE REVIEW

**Review by MoribundMedium — CHANGES_REQUESTED** [review]
Hi @christianzoll, your previous PR included a file `src/assets/pick-32.png`. Is `src/images/FCC-Nashville-orange-logo.svg` the correct image and already included in the repo?

Additionally, the PR now deletes the entirety of `package-lock.json`. If your goal is to make zero changes to the file, I recommend dropping back to a previous commit, copying that file, and making a new commit with it. Let me know if you need me to explain further.

**Review by rjfuhrman42 — APPROVED** [review]

**Review by MoribundMedium — CHANGES_REQUESTED** [review]
Hi @christianzoll! As we discussed before, the font isn't quite working in the SVG that we're using for the favicon. I took a screenshot of the icon and added a transparent background and saved it as a PNG. I made a 32x32 image that we can use, and a default 400x400 version in case we want to scale it down to 64x64 or anything else.

Think we can swap these in for the SVG?

favicon-32
favicon-400

**Review by Hellrungj — APPROVED** [review]
Looks great. 👍

**Review by MoribundMedium — APPROVED** [review]

**Comment by MoribundMedium** [comment]
I think we're all good! Great work!

**Pull request merged**
