### PR TITLE
Re-Reinstalling Tailwind

### PR DESCRIPTION
**Pull request by meltonlogan615**
Inverted Morbius Strip

### CODE REVIEW

**Comment by bestyoucanbe** [comment]
[Git Bash View.pdf](https://github.com/nashvillefcc/nashvillefcc2020website/files/4565712/Git.Bash.View.pdf)

This is the view I get when I execute NPM start on this branch.

**Comment by bestyoucanbe** [comment]
[Chrome Browser Views.pdf](https://github.com/nashvillefcc/nashvillefcc2020website/files/4566008/Chrome.Browser.Views.pdf)

This is view from the Chrome browser and the second screen dump shows the console error due to changing it from a <li> item to a <Link> item on the menu.

**Comment by meltonlogan615** [comment]
What's the current status on this? Is there something that I need to do to get this back in motion?

**Comment by bestyoucanbe** [comment]
@meltonlogan615  -- Shall we use this pull request as your completion of the installation of Tailwind (rather than https://github.com/nashvillefcc/nashvillefcc2020website/pull/19 )?

**Comment by meltonlogan615** [comment]
If John was able to get it to run and resolve the the errors, then absolutely.

**Pull request merged**
