### PR TITLE
Removing GitHub Pages

### LINKED ISSUE #50: Netlify hosting
# Acceptance Criteria
Get this site served up over Netlify instead of Github Pages. The build process should be automated and current build files (in /doc folder) should be removed from repo. A document should be introduced detailing our new process

A domain name will need to be acquired at some point, but that is not considered part of the scope of this ticket unless it is needed by Netlify.

### Related Features
- N/A

### Resources
- https://www.netlify.com/with/gatsby/

### PR DESCRIPTION
**Pull request by MoribundMedium**
Resolves #50
# Description of Changes
Removed the `/docs` folder and its contents from our repository, and removed the pathPrefix property from our configs. They were only being used by GitHub Pages and won't be necessary when we switch to Netlify. I'll remove the GitHub Pages settings from this repo once the PR is merged.

The site is currently being built on Netlify from the `master` branch, whenever there's a merge. Netlify settings were set up by the project owner, so I don't currently have access to them, but they can be peer reviewed once the project gets an OSS license from the company. Its address is at https://fcc-nashville.netlify.app/.

### CODE REVIEW

**Review by tylermwatts — APPROVED** [review]

**Review by rjfuhrman42 — APPROVED** [review]

**Review by christianzoll — COMMENTED** [review]
Cleared up questions about deleted files in meeting.

**Review by Hellrungj — APPROVED** [review]
Thanks for cleaning that up! 👍

**Review by Hellrungj — APPROVED** [review]
Thanks for updating the config files and removing old config properties. 👍

**Review by christianzoll — COMMENTED** [review]
All's understood

**Pull request merged**
